// Exact acquisition statements verified against aggregate Warframe Wiki
// source pages when an item's individual page does not expose the statement.
// Keep these keyed by DE uniqueName so similarly named objects cannot inherit
// an acquisition route by accident.
export const WIKI_VERIFIED_ACQUISITIONS = new Map([
  [
    '/Lotus/Upgrades/Skins/Operator/Skirts/SkirtAdultPrimeB',
    {
      text: 'Component of the Commodore Prime Suit, included in the Zephyr Prime Accessories package during Zephyr Prime Access; the local export links this Drifter/Operator piece to its Prime armor counterpart.',
      url: 'https://www.warframe.com/news/zephyr-prime-access-begins-march-20',
      source: 'Warframe.com Zephyr Prime Access announcement + local export Commodore Prime component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/BodySuits/BodySuitAdultPrimeB',
    {
      text: 'Component of the Commodore Prime Suit, included in the Zephyr Prime Accessories package during Zephyr Prime Access; the local export links this Drifter/Operator piece to its Prime armor counterpart.',
      url: 'https://www.warframe.com/news/zephyr-prime-access-begins-march-20',
      source: 'Warframe.com Zephyr Prime Access announcement + local export Commodore Prime component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/Leggings/LeggingsAdultPrimeB',
    {
      text: 'Component of the Commodore Prime Suit, included in the Zephyr Prime Accessories package during Zephyr Prime Access; the local export links this Drifter/Operator piece to its Prime armor counterpart.',
      url: 'https://www.warframe.com/news/zephyr-prime-access-begins-march-20',
      source: 'Warframe.com Zephyr Prime Access announcement + local export Commodore Prime component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/Hoods/HoodAdultPrimeB',
    {
      text: 'Component of the Commodore Prime Suit, included in the Zephyr Prime Accessories package during Zephyr Prime Access; the local export links this Drifter/Operator piece to its Prime armor counterpart.',
      url: 'https://www.warframe.com/news/zephyr-prime-access-begins-march-20',
      source: 'Warframe.com Zephyr Prime Access announcement + local export Commodore Prime component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/Sleeves/SleevesAdultPrimeB',
    {
      text: 'Component of the Commodore Prime Suit, included in the Zephyr Prime Accessories package during Zephyr Prime Access; the local export links this Drifter/Operator piece to its Prime armor counterpart.',
      url: 'https://www.warframe.com/news/zephyr-prime-access-begins-march-20',
      source: 'Warframe.com Zephyr Prime Access announcement + local export Commodore Prime component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Dagath/DagathDeluxeLNYHelmet',
    {
      text: 'Included with the Dagath Yfari Skin; the skin is sold individually in the in-game Market for 165 Platinum, and the local export links this helmet as its component.',
      url: 'https://www.warframe.com/en/patch-notes/pc/41-1-0',
      source: 'Warframe.com Update 41.1: Vauban Heirloom + local export Dagath Yfari skin/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Armor/WarframeDefaults/SWYhavanDagathAArmor',
    {
      text: 'Included with the Dagath Yhavan Skin; PC players acquire the TennoGen skin through Steam Workshop, while console and iOS players can purchase it for Platinum in the in-game Market.',
      url: 'https://forums.warframe.com/topic/1469559-new-tennogen-arriving-in-october-first-look/',
      source: 'Warframe Forums TennoGen announcement + local export Dagath Yhavan skin/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/BrokenFrame/XakuCosmosSkin',
    {
      text: 'Nora’s Mix Volume 9 reward at Rank 30; the reward included the Xaku Raya Skin and Xaku Raya Helmet.',
      url: 'https://wiki.warframe.com/w/Nightwave/Nora%27s_Mix_Volume_9',
      source: 'Warframe Wiki (Nora’s Mix Volume 9) + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/BrokenFrame/XakuCosmosHelmet',
    {
      text: 'Nora’s Mix Volume 9 reward at Rank 30, included with the Xaku Raya Skin.',
      url: 'https://wiki.warframe.com/w/Nightwave/Nora%27s_Mix_Volume_9',
      source: 'Warframe Wiki (Nora’s Mix Volume 9) + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Trapper/VaubanHeirloomHelmet',
    {
      text: 'Included with the Vauban Heirloom Skin in the Vauban Heirloom Collection; the local export lists the skin at 225 Platinum and the collection at 400 Platinum.',
      url: 'https://www.warframe.com/en/patch-notes/pc/41-1-0',
      source: 'Warframe.com Update 41.1: Vauban Heirloom + local export skin/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Trapper/VaubanHeirloomAux',
    {
      text: 'Included with the Vauban Heirloom Skin in the Vauban Heirloom Collection; the Overcoat can be switched to its sleeveless variant in the Auxiliary options.',
      url: 'https://www.warframe.com/en/patch-notes/pc/41-1-0',
      source: 'Warframe.com Update 41.1: Vauban Heirloom + local export skin/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Trapper/VaubanHeirloomAuxSleeveless',
    {
      text: 'The sleeveless Overcoat option is included with the Vauban Heirloom Skin in the Vauban Heirloom Collection.',
      url: 'https://www.warframe.com/en/patch-notes/pc/41-1-0',
      source: 'Warframe.com Update 41.1: Vauban Heirloom + local export skin/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Necramech/VoidrigDOTDSkin',
    {
      text: 'Purchased from Daughter during Nights of Naberus for 100 Mother Tokens; the linked Day of the Dead Necramech Helmet is granted with the skin.',
      url: 'https://warframe.fandom.com/wiki/Necramech',
      source: 'Warframe Wiki (Necramech) + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Necramech/VoidrigDOTDHelmet',
    {
      text: 'Granted with the Day of the Dead Necramech Skin, which is purchased from Daughter during Nights of Naberus for 100 Mother Tokens.',
      url: 'https://warframe.fandom.com/wiki/Necramech',
      source: 'Warframe Wiki (Necramech) + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Necramech/TefilahIridosSkin',
    {
      text: 'Prime Gaming Drop 12: claim the Iridos Collection through a linked Prime Gaming and Warframe account; the drop included the Iridos Voidrig Necramech Skin and its helmet.',
      url: 'https://www.warframe.com/en/news/prime-gaming-iridos-collection',
      source: 'Warframe.com Prime Gaming Iridos Collection + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Necramech/TefilahIridosHelmet',
    {
      text: 'Prime Gaming Drop 12: claim the Iridos Collection through a linked Prime Gaming and Warframe account; the drop included the Iridos Voidrig Necramech Skin and this helmet.',
      url: 'https://www.warframe.com/en/news/prime-gaming-iridos-collection',
      source: 'Warframe.com Prime Gaming Iridos Collection + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Bard/BardTwitchSkin',
    {
      text: 'Prime Gaming Drop 1: the Octavia Iridos Bundle, available through November 14, 2023, included Octavia Iridos Skin and the Octavia Iridos Mix Helmet.',
      url: 'https://www.warframe.com/en/news/prime-gaming-iridos-collection',
      source: 'Warframe.com Prime Gaming Iridos Collection',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Bard/BardTwitchAltHelmet',
    {
      text: 'Included in the Octavia Iridos Bundle from Prime Gaming, available through November 14, 2023, as the Octavia Iridos Mix Helmet.',
      url: 'https://www.warframe.com/en/news/prime-gaming-iridos-collection',
      source: 'Warframe.com Prime Gaming Iridos Collection',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Necramech/NecramechSnakeSkin',
    {
      text: 'Purchased from the Necraloid Syndicate’s Necramech Embellishments offerings for 60 Platinum.',
      url: 'https://warframe.fandom.com/wiki/Necramech',
      source: 'Warframe Wiki (Necramech) + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Necramech/NecramechSnakeHelmet',
    {
      text: 'Granted with the Snake Necramech Skin, purchased from the Necraloid Syndicate’s Necramech Embellishments offerings for 60 Platinum.',
      url: 'https://warframe.fandom.com/wiki/Necramech',
      source: 'Warframe Wiki (Necramech) + local export skin/helmet relationship',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Sigils/NecramechSigilSnake',
    {
      text: 'Purchased from the Necraloid Syndicate’s Necramech Embellishments offerings for 40 Platinum.',
      url: 'https://warframe.fandom.com/wiki/Necramech',
      source: 'Warframe Wiki (Necramech)',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/Skirts/SkirtLasrianB',
    {
      text: 'Included in the Chymerist Collection (130 Platinum), or obtained with the corresponding Chymerist Apparel purchase for 25 Platinum; the Operator and Drifter versions are linked in the export.',
      url: 'https://www.warframe.com/ru/patch-notes/pc/38-5-0',
      source: 'Warframe.com Techrot Encore Update 38.5 + local export Chymerist bundle/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/Sleeves/SleevesOperatorLasrianB',
    {
      text: 'Included in the Chymerist Collection (130 Platinum), or obtained with the corresponding Chymerist Gloves purchase for 30 Platinum; the Operator and Drifter versions are linked in the export.',
      url: 'https://www.warframe.com/ru/patch-notes/pc/38-5-0',
      source: 'Warframe.com Techrot Encore Update 38.5 + local export Chymerist bundle/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/Hoods/HoodOperatorLasrianB',
    {
      text: 'Included in the Chymerist Collection (130 Platinum), or obtained with the corresponding Chymerist Mask purchase for 40 Platinum; the Operator and Drifter versions are linked in the export.',
      url: 'https://www.warframe.com/ru/patch-notes/pc/38-5-0',
      source: 'Warframe.com Techrot Encore Update 38.5 + local export Chymerist bundle/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Operator/BodySuits/BodySuitOperatorLasrianB',
    {
      text: 'Included in the Chymerist Collection (130 Platinum), or obtained with the corresponding Chymerist Uniform purchase for 40 Platinum; the Operator and Drifter versions are linked in the export.',
      url: 'https://www.warframe.com/ru/patch-notes/pc/38-5-0',
      source: 'Warframe.com Techrot Encore Update 38.5 + local export Chymerist bundle/component records',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Armor/PrimeStyanaxArmor/PrimeStyanaxCArmor',
    {
      text: 'Component of Daurus Prime Armor, included in the Styanax Prime Accessories Pack and Styanax Prime Access Complete Pack; this was a limited-time Prime Access offering.',
      url: 'https://www.warframe.com/prime-access',
      source: 'Warframe Prime Access (Styanax Prime Accessories)',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Armor/PrimeStyanaxArmor/PrimeStyanaxLArmor',
    {
      text: 'Component of Daurus Prime Armor, included in the Styanax Prime Accessories Pack and Styanax Prime Access Complete Pack; this was a limited-time Prime Access offering.',
      url: 'https://www.warframe.com/prime-access',
      source: 'Warframe Prime Access (Styanax Prime Accessories)',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Armor/PrimeStyanaxArmor/PrimeStyanaxAArmor',
    {
      text: 'Component of Daurus Prime Armor, included in the Styanax Prime Accessories Pack and Styanax Prime Access Complete Pack; this was a limited-time Prime Access offering.',
      url: 'https://www.warframe.com/prime-access',
      source: 'Warframe Prime Access (Styanax Prime Accessories)',
    },
  ],
  [
    '/Lotus/Upgrades/Skins/Geode/CitrineDeluxeHelmet',
    {
      text: 'Included with the Citrine Aphrodita Skin; the skin is sold individually in the Market for 165 Platinum or in the Citrine Aphrodita Collection for 365 Platinum.',
      url: 'https://www.warframe.com/pt-br/patch-notes/ios/39-0-0',
      source: 'Warframe.com Isleweaver Update 39; Warframe Wiki (Citrine Aphrodita Skin)',
    },
  ],
  [
    '/Lotus/Types/AvatarImages/Community10YearOrdisGlyph',
    {
      text: 'Part of the 10 Year Anniversary Community Art Pack, purchased in the Market for 70 Platinum.',
      url: 'https://wiki.warframe.com/w/Glyph',
      source: 'Warframe Wiki (Glyph)',
    },
  ],
  ['/Lotus/Types/AvatarImages/AvatarImageBuriedDebts', { text: 'Redeem the promo code THEDEADHAVEDEBTS from Operation: Buried Debts.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageCephalonCy', { text: 'Twitch, Mixer, or Steam Drop for watching an official Warframe stream for 30 minutes during the launch of Update 27.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageCephalonSimaris', { text: "Exclusively awarded to winners of Simaris' Sanctuary Showdown during TennoCon 2018, distributed via a code card after the event.", url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/CherryTreeGlyph', { text: 'Twitch Drop for watching Partner streams for 1 hour during the launch of Update 23.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Warframes/CitrineActionGlyph', { text: 'Awarded from the Gift from the Lotus alert on April 5, 2023.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Seasonal/AvatarImageHalloween2021Dethcube', { text: 'Included in the Gruesome Glyph Bundle, sold in the Market for 65 Platinum during Halloween since 2021.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2017A', { text: 'Included in the Donwyn Glyph Pack, sold in the Market for 80 Platinum during Valentines 2017.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2017B', { text: 'Included in the Donwyn Glyph Pack, sold in the Market for 80 Platinum during Valentines 2017.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2017C', { text: 'Included in the Donwyn Glyph Pack, sold in the Market for 80 Platinum during Valentines 2017.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2017D', { text: 'Included in the Donwyn Glyph Pack, sold in the Market for 80 Platinum during Valentines 2017.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2017E', { text: 'Included in the Donwyn Glyph Pack, sold in the Market for 80 Platinum during Valentines 2017.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2020Alad', { text: 'Included in Donwyn Glyph Pack II, sold in the Market for 60 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2020Clem', { text: 'Included in Donwyn Glyph Pack II, sold in the Market for 60 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2020Key', { text: 'Included in Donwyn Glyph Pack II, sold in the Market for 60 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2020Kuva', { text: 'Included in Donwyn Glyph Pack II, sold in the Market for 60 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TenYearAnniversaryWeek2Glyph', { text: 'Given to all players who completed the Recall Ten-Zero quests during the July 19–August 25 anniversary period.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageDeadlockProtocolB', { text: 'Redeem the promo code aungelecette-dlp, issued June 11, 2020.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageGengzi', { text: 'Available from the Market for 1 Credit from January 23–31, 2020; Lunar New Year exclusive.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Seasonal/AvatarImageHalloween2021Grineer', { text: 'Included in the Gruesome Glyph Bundle, sold in the Market for 65 Platinum during Halloween since 2021.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageInktober', { text: "Given to all eligible participants of Halloween's Tennotober contest.", url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TenYearAnniversaryWeek4Glyph', { text: 'Given to all players who completed the Recall Ten-Zero quests during the July 19–August 25 anniversary period.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphJingleKavat', { text: 'Included in Winter Glyph Pack IV, sold for 90 Platinum during Christmas 2019.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphJollyGrendel', { text: 'Included in Winter Glyph Pack IV, sold for 90 Platinum during Christmas 2019.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Xmas2021GrinoalieGlyph', { text: 'Tennobaum 2022 milestone reward.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageKhoraInAction', { text: "Nightwave reward from Nora's Mix Volume 6.", url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageOroKitty', { text: 'Rewarded upon scanning 75% of Kuria.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageAmirValentine', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageAoiValentine', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageArthurValentine', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageStarDaysCervulitePat', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageEleanorValentine', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2023Gyre', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2023Kavat', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageLettieValentine', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageStarDaysQorvexHeart', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageQuincyValentine', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageValentine2023Ticker', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageBadgeEmber', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageBadgeKulervo', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageBadgeMesa', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageBadgeOctavia', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageBadgeRhino', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageBadgeStynax', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageBadgeXaku', { text: 'Purchased from Ticker in Fortuna during Star Days for 5 specified Debt-Bonds.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TenYearAnniversaryWeek3Glyph', { text: 'Given to all players who completed the Recall Ten-Zero quests during the July 19–August 25 anniversary period.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TenYearAnniversaryWeek5Glyph', { text: 'Given to all players who completed the Recall Ten-Zero quests during the July 19–August 25 anniversary period.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TenYearAnniversaryWeek1Glyph', { text: 'Given to all players who completed the Recall Ten-Zero quests during the July 19–August 25 anniversary period.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageStarterPackLotus', { text: 'Available through the WARFRAME Starter Pack from June 25, 2019 until August 25, 2020.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphStarterPackA', { text: 'Available through the WARFRAME Starter Pack until June 25, 2019.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageRailjackInAction', { text: 'Available through the Empyrean Supporter Pack from December 12, 2019 until August 25, 2020.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGrineerQueensVed', { text: 'Rewarded upon completing The War Within.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Image2019Twitter', { text: 'Redeem the promo code TWEET4TENNO during TennoCon 2019.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Gamification2019Glyph', { text: 'Reward for completing the TennoCon 2019 scavenger-hunt-style game.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2020SimarisGlyph', { text: 'Exclusive reward for the top 1,000 highest-scoring players of the TennoTrivia quiz during TennoCon 2020.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/FanChannel/AvatarImageTennoGen', { text: 'Included in the TennoGen Glyph Pack, sold in the Market for 75 Platinum; also purchasable individually for 15 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2017Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2017 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2018Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2018 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2019Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2019 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2020Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2020 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2021Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2021 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2022Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2022 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2023Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2023 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2024Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2024 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2025Glyph', { text: 'Exclusive to players who purchased the physical or digital TennoCon 2025 ticket.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2021MerchGlyph', { text: 'Part of the purchasable TennoCon 2021 merch pack, obtained with its redeemable code.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2022MerchGlyph', { text: 'Part of the purchasable TennoCon 2022 merch pack, obtained with its redeemable code.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageDeadlockProtocolA', { text: 'Redeem the promo code GOLDEN, issued before the launch of The Deadlock Protocol.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageZarimanLogo', { text: 'Redeem the promo code REMEMBERUS, issued April 28, 2022.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Xmas2021MaggotGlyph', { text: 'Tennobaum 2022 milestone reward.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Xmas2021MoaGlyph', { text: 'Tennobaum 2022 milestone reward.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Xmas2021NutcorpusGlyph', { text: 'Tennobaum 2022 milestone reward.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Xmas2023ThraxGlyph', { text: 'Tennobaum 2023 milestone reward.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Xmas2023BombastineGlyph', { text: 'Part of the Duviri Community Art Pack, sold in the Market for 40 Platinum; the glyph is also available individually for 20 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageDexAnniversary', { text: 'Reward from the 7th Year Anniversary alert.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageConqueraGlyphUpdated', { text: 'Available from the Market for 1 Credit during the Conquera campaign.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/FanChannel/AvatarImageLegendaryElof', { text: 'Exclusive to the player who designed it after purchasing a Legendary Ticket to TennoCon.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphKiradien', { text: 'Exclusive to the player who designed it after purchasing a Legendary Ticket to TennoCon.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphLegendaryCelestics', { text: 'Exclusive to the player who designed it after purchasing a Legendary Ticket to TennoCon.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphMattaus', { text: 'Exclusive to the player who designed it after purchasing a Legendary Ticket to TennoCon.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageLotusDeluxe', { text: 'Included in the Golden Mend Collection, sold in the Market for 430 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Seasonal/AvatarImageHalloween2021Loid', { text: 'Included in the Gruesome Glyph Bundle, sold in the Market for 65 Platinum during Halloween since 2021.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Seasonal/AvatarImageHalloween2021Pumpkin', { text: 'Included in the Gruesome Glyph Bundle, sold in the Market for 65 Platinum during Halloween since 2021.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImagePrideCommunity', { text: 'Available from the Market for 1 Credit during Pride in June.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageHildrynPrideCommunity', { text: 'Available from the Market for 1 Credit during Pride in June.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphSkiGauss', { text: 'Included in Winter Glyph Pack IV, sold for 90 Platinum during Christmas 2019.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageGlyphSurpriseIvara', { text: 'Included in Winter Glyph Pack IV, sold for 90 Platinum during Christmas 2019.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/TennoCon2023MerchGlyph', { text: 'Awarded to the top 10 of the 10 Year Anniversary Art Showcase; winners were announced April 20, 2023.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageTennoVIP', { text: 'Available through the 11 Year Anniversary Twitch Drop campaign.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/AvatarImageTeshinVed', { text: 'Redeem the promo code WARWITHIN during the launch of Update 19.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/FanChannel/AvatarImageLegendaryBlackdeath', { text: 'Exclusive to the player who designed it after purchasing a Legendary Ticket to TennoCon.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/ImageXakuDeluxeKintsugi', { text: 'Included in the Golden Mend Collection, sold in the Market for 430 Platinum.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Seasonal/AvatarImageHalloween2024SisterNoBloodGlyph', { text: 'Purchased from Daughter for 20 Mother Tokens during Nights of Naberus.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Types/AvatarImages/Seasonal/AvatarImageHalloween2021Lotus', { text: 'Included in the Gruesome Glyph Bundle, sold in the Market for 65 Platinum during Halloween since 2021.', url: 'https://wiki.warframe.com/w/Glyph', source: 'Warframe Wiki (Glyph)' }],
  ['/Lotus/Upgrades/Skins/Sigils/InfLichConvertedSigil', {
    text: 'Rewarded for converting your first Technocyte Coda.',
    url: 'https://www.warframe.com/en/patch-notes/psn/38-5-0',
    source: 'Warframe.com Update 38.5: Techrot Encore',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/InfLichVanquishedSigil', {
    text: 'Rewarded for vanquishing your first Technocyte Coda.',
    url: 'https://www.warframe.com/en/patch-notes/psn/38-5-0',
    source: 'Warframe.com Update 38.5: Techrot Encore',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/HoundingKubrowSigil', {
    text: 'Purchased from Daughter in the Necralisk during Nights of Naberus for Mother Tokens.',
    url: 'https://www.warframe.com/th/news/nights-of-naberus-returns-en',
    source: 'Warframe.com Nights of Naberus Returns',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/SomberStalkerSigil', {
    text: 'Purchased from Daughter in the Necralisk during Nights of Naberus for Mother Tokens.',
    url: 'https://www.warframe.com/th/news/nights-of-naberus-returns-en',
    source: 'Warframe.com Nights of Naberus Returns',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/Tennogen10YearSigil', {
    text: 'Free Inbox reward during the TennoGen 10 Year Anniversary campaign; claimable by logging in before December 31, 2025.',
    url: 'https://www.warframe.com/en/news/tennogen10',
    source: 'Warframe.com TennoGen 10 Year Anniversary Celebration',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/PS4TwoYearSigil', {
    text: 'PS4 second-anniversary Inbox reward during the 2015 anniversary event.',
    url: 'https://www.warframe.com/uk/news/warframe-celebrates-two-years-playstation-4',
    source: 'Warframe.com PlayStation 4 second anniversary announcement',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/PS4FourYearSigil', {
    text: 'PS4 fourth-anniversary Inbox reward during the 2017 anniversary event.',
    url: 'https://www.warframe.com/en/news/playstation-4',
    source: 'Warframe.com PlayStation 4 fourth anniversary announcement',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/PS4FiveYearSigil', {
    text: 'PS4 fifth-anniversary Inbox reward during the 2018 anniversary event.',
    url: 'https://www.warframe.com/en/news/5-year-anniversary',
    source: 'Warframe.com PlayStation 4 fifth anniversary announcement',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/XBoneTwoYearSigil', {
    text: 'Xbox second-anniversary Inbox reward during the 2016 anniversary event.',
    url: 'https://www.warframe.com/uk/news/dziekujemy-za-dwa-wysmienite-lata-tenno',
    source: 'Warframe.com Xbox One second anniversary announcement',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/XBoneFourYearSigil', {
    text: 'Xbox fourth-anniversary Inbox reward during the 2018 anniversary event.',
    url: 'https://www.warframe.com/en/news/warframe-s-fourth-anniversary-on-xbox-one',
    source: 'Warframe.com Xbox One fourth anniversary announcement',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/PS4CrowSigil', {
    text: 'Included in the PlayStation-exclusive Obsidian Corvus Collection.',
    url: 'https://www.warframe.com/uk/news/obsidian-corvus-collection-available-now',
    source: 'Warframe.com Obsidian Corvus Collection announcement',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/ObsidianIndraSigil', {
    text: 'Included in the PlayStation-exclusive Ultimate Obsidian Collection.',
    url: 'https://www.warframe.com/en/news/ultimate-obsidian-collection',
    source: 'Warframe.com Ultimate Obsidian Collection announcement',
  }],
  ['/Lotus/Upgrades/Skins/Sigils/PS4RenownXSigil', {
    text: 'Included in the PlayStation-exclusive Renown Pack X.',
    url: 'https://www.warframe.com/en/news/x',
    source: 'Warframe.com Renown Pack X announcement',
  }],
]);
